// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwQ3-dKBqySse8PemBNpjyM6g440r3Tm0',
    appId: '1:765825127964:web:432ad457d481156275f1d9',
    messagingSenderId: '765825127964',
    projectId: 'flipcart-7f365',
    authDomain: 'flipcart-7f365.firebaseapp.com',
    storageBucket: 'flipcart-7f365.appspot.com',
    measurementId: 'G-8CWEV49H45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpmpO_3mjh4qgQg9WzFshcazshEvLilpc',
    appId: '1:765825127964:android:5d701083239a02d575f1d9',
    messagingSenderId: '765825127964',
    projectId: 'flipcart-7f365',
    storageBucket: 'flipcart-7f365.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMd0Q1O9yjWXvCWMXISOR_14lhYUo3-4o',
    appId: '1:765825127964:ios:0ebcfbe86e17ca7175f1d9',
    messagingSenderId: '765825127964',
    projectId: 'flipcart-7f365',
    storageBucket: 'flipcart-7f365.appspot.com',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMd0Q1O9yjWXvCWMXISOR_14lhYUo3-4o',
    appId: '1:765825127964:ios:0ebcfbe86e17ca7175f1d9',
    messagingSenderId: '765825127964',
    projectId: 'flipcart-7f365',
    storageBucket: 'flipcart-7f365.appspot.com',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwQ3-dKBqySse8PemBNpjyM6g440r3Tm0',
    appId: '1:765825127964:web:a61bbf95ee7cf8bc75f1d9',
    messagingSenderId: '765825127964',
    projectId: 'flipcart-7f365',
    authDomain: 'flipcart-7f365.firebaseapp.com',
    storageBucket: 'flipcart-7f365.appspot.com',
    measurementId: 'G-SGN02EQZGP',
  );
}
